import './styles/globals.scss'
import 'bootstrap/dist/css/bootstrap.min.css';
import "slick-carousel/slick/slick.css"; 
import "slick-carousel/slick/slick-theme.css";



 // 1. Jokhon html/css use kori tokhon prothom sass er jei class nisilo oibhabe korbo. tokhon protita jinish er jonno alada folder create korte hobe. jemon mixin, variable, component er jonno alada folder create korte hobe. Html/css er jonno mixin use korbo font-size, color, background etc er jonno mixin use korbo
  // 2. react/next er jonno sass er jonno alada kore component ba variable er folder create korte hobe na. karon eder jonno alada folder emnei ache. tai ar lagbe na. tarpor Js er framwork(react/next) er jonno mixin tokhon ee use korbo shudhu responsive er jonno

  // App er bhitore jei layout.js ache oita hocche react er index.js er moto. 
  // react er index.html file jeta chilo oigulao shob ei layout.js e link korte hobe 
  // html er bhitore head tag chilo jeta next e nai. kintu ekhane bodyr upore head tag likhe chailei head tag er kaaj korte pari 

  // extension e js ar jsx er difference holo. by default jegula javascript er banano js file ache oigular extension ke js dibo. jemon Navbar.js/footer.js etc. Kintu jegula amar nijer banano js file oigular extension jsx dibo example Menubar.jsx/Menudata.jsx. Eta mandatory na. je jeita chay dite pare

  // Slick Slider emon ek jaygay import korte hobe jeita shob jaygay pabe 

  // Mapping er 2nd parameter(item, i) dawar karon hocche index number er jonno 



  // Bootstrap devices 
  // xs device: 0-575px
  // sm device: 576-767px 
  // md device: 768-991px 
  // lg device: 992-1199px
  // xl device: 1200-1399px
  // xxl device: 1400-1600px 

export const metadata = {
  title: 'My Portfolio',
  description: 'Generated by Taufik Mahbub',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  )
}
